In [2]:
# %tensorflow_version 2.x # This tells a online notebook to use 2.x version
import tensorflow as tf
print(tf.__version__)

2023-07-21 17:44:46.758066: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-21 17:44:46.769289: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 17:44:46.848158: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 17:44:46.849570: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-21 17:44:47.521475: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

2.13.0


In [3]:
string = tf.Variable("Value of string", tf.string)
number = tf.Variable(123, tf.int16)
float = tf.Variable(12.0, tf.float64)

In [5]:
# Any array has automatic rank 1 minimum. Rank is just dimnension of matrix
rank1_tensor = tf.Variable(["a","b"], tf.string)
# Multi-dimensional elements must be uniform
rank2_tensor = tf.Variable([["a","b"],["c","d"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
# Shape is the depth of the dimension
# tf.shape(rank2_tensor)
rank2_tensor.shape

TensorShape([2, 2])

In [8]:
# Create (one) matrix with (2) dimensions, of (3) elements each
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [3,-1]) # a negative here means, figure it out

print(tensor1)
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
# 4 types of tensor: Variable, Constant, Placeholder, SparseTensor
# In order to execute a tensor, a session needs to be created

with tf.Session() as sess: # creates a sessions using the default graph
    tensor.eval()
    